### ISSUE TITLE
Anyone manage to enable keycloak authentication?

### ISSUE THREAD

**Issue by holmesb** [minio/charts#107]
Hi, would be great if someone who has successfully enabled keycloak oauth using this chart could share their values.  We've followed [this guide](https://github.com/minio/minio/blob/master/docs/sts/keycloak.md) and have set the following values:
```
environment:
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: <our_root_password>
  MINIO_IDENTITY_OPENID_CONFIG_URL: https://<our_keycloak_server>/auth/realms/<our_realm>/.well-known/openid-configuration
  MINIO_IDENTITY_OPENID_CLIENT_ID: <our_client_id_in_long_random_UUID_format>
```
But after redeploying the chart we don't see any "Log in with OpenID" on the home page.  In a shell session on the minio pod, I can see these env vars have successfully arrived.  But minio doesn't seem to have loaded them:
```
mc admin config get minio identity_openid
identity_openid config_url= client_id= claim_name=policy claim_prefix= scopes= jwks_url=
```
The mc command is operational, as we can `mc ls minio` and see our buckets.  Any ideas?

**Comment by jgato** [comment]
I am in the same situation, starting to integrate with Keycloak. Did you have any progress about this?

**Comment by jgato** [comment]
Well, in my case, just adding:

```
environment:
    MINIO_IDENTITY_OPENID_CONFIG_URL: "https://keycloak.foo.bar/realms/realm-name/.well-known/openid-configuration" 
    MINIO_IDENTITY_OPENID_CLIENT_ID: "client-id"
    MINIO_IDENTITY_OPENID_SCOPES: "email"
    MINIO_IDENTITY_OPENID_CLAIM_NAME: "https://min.io/policy"
```
seems to enable OpenID login:

![image](https://user-images.githubusercontent.com/3435696/112132469-f41b0c00-8bca-11eb-9156-f005d05de7fd.png)

then it redirects to Keycloak, make the login (login seems succesfull), but I have a 502 Bad Gateway :(
