### ISSUE TITLE
Not run as root for job pod containers

### ISSUE THREAD

**Issue by mitchellmaler** [minio/charts#16]
We require all pods to not run as root except for specific reasons. We could create a pod security policy and service account just for these job pods but wanted to see if they could be enhanced/changed to just not run as root by default?

**Comment by harshavardhana** [comment]
Run it with a security policy @mitchellmaler default podSecurity is 

```
## Add stateful containers to have security context, if enabled MinIO will run as this
## user and group NOTE: securityContext is only enabled if persistence.enabled=true
securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
```
