### ISSUE TITLE
Gitlab runner job often failing with 137 error while trying to download cache from MinIO

### ISSUE THREAD

**Issue by kumarpratyush** [minio/charts#26]
First off, I know this might not be a MinIO issue, but I am trying to check all possible actors involved in my system to find out the root cause. 
We are using MinIO cache to upload dependencies for our gradle project and we download the same before building the project. Lately, we are seeing a lot of 137 errors while trying to download the cache from minio server. 

Details : 
**MinIO version** -- minio-5.0.33
**Gitlab-runner version** - gitlab-runner-0.20.1
**MinIO cache size** -- 650MB
**Error stack trace :** 
```
Restoring cache
Checking cache for default-11...
Downloading cache.zip from http://[MASKED]-minio.default.svc.cluster.local:9000/[MASKED]-minio-cache/gitlab_runner/project/321/default-11 
Uploading artifacts for failed job
ERROR: Job failed: command terminated with exit code 137
```
**Helper container config for Gitlab runner (used to download cache)**:
```
helpers:
     cpuLimit: 300m
     memoryLimit: 1000Mi
     cpuRequests: 300m
     memoryRequests: 1000Mi
```

**Minio chart yaml :**
```
clusterDomain: cluster.local
image:
  repository: minio/minio
  tag: RELEASE.2019-08-07T01-59-21Z
  pullPolicy: IfNotPresent
mcImage:
  repository: minio/mc
  tag: RELEASE.2019-08-07T23-14-43Z
  pullPolicy: IfNotPresent

mode: standalone
DeploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%
StatefulSetUpdate:
  updateStrategy: RollingUpdate
priorityClassName: ""

existingSecret: ""
accessKey: "cacheKey"
secretKey: "secret"
configPath: "/root/.minio/"
configPathmc: "/root/.mc/"
mountPath: "/export"
replicas: 4

## TLS Settings for Minio
tls:
  enabled: false
  certSecret: ""
  publicCrt: public.crt
  privateKey: private.key

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi

  subPath: ""
service:
  type: ClusterIP
  clusterIP: ~
  port: 9000
  nodePort: 31311
  annotations: {}
ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
nodeSelector:
  node-type: master-node
tolerations: []
affinity: {}

podAnnotations: {}

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

resources:
  requests:
    memory: 256Mi
    cpu: 250m
defaultBucket:
  enabled: true
  name: consumer-app-minio-cache
  policy: public
  purge: false

buckets: []
s3gateway:
  enabled: false
  replicas: 4
  serviceEndpoint: ""

azuregateway:
  enabled: false
  # Number of parallel instances
  replicas: 4
gcsgateway:
  enabled: false
  # Number of parallel instances
  replicas: 4
  # credential json file of service account key
  gcsKeyJson: ""
  # Google cloud project-id
  projectId: ""

ossgateway:
  enabled: false
  # Number of parallel instances
  replicas: 4
  endpointURL: ""

nasgateway:
  enabled: false
  # Number of parallel instances
  replicas: 4
  # For NAS Gateway, you may want to bind the PVC to a specific PV. To ensure that happens, PV to bind to should have
  # a label like "pv: <value>", use value here.
  pv: ~

environment:
  ## To disable Minio Browser, set this value to off
  MINIO_BROWSER: "on"
  MINIO_CACHE_EXPIRY: "7"
networkPolicy:
  enabled: false
  allowExternal: true

serviceAccount:
  create: true
  name:

metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}

```
