### ISSUE TITLE
Unable to download files from outside the Kubernetes cluster because of the shared URL.

### ISSUE THREAD

**Issue by SebiBurchi** [minio/charts#57]
I am trying to set up MinIO in kubernetes cluster behind nginx ingress controller and access shared files through ingress path. 
My configuration from **values.yaml**:
```
minio:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
    hosts:
      - ""
    path: /minio
  accessKey: minioKey
  secretKey: minioKey
```

**### WEB BROWSER CLIENT**
Uploading a file works properly. I access the MinIO through ingress using` https://{CLUSTER_IP}:{PORT}/minio`

**### THE PROBLEM**
The problem is when I am trying to download the file uploaded before, from outside the cluster.
Checking the shared URL in web browser, the result is:  `https://{CLUSTER_IP}/{bucket}/{file_name}` instead of `https://{CLUSTER_IP}/**minio**/{bucket}/{file_name}`
Because of the absence of `minio` part in the URL, I can't download the file, from outside the cluster, using curl/wget etc. Without `minio `in the URL, I am redirected to the default path of my ingress controller ("/"), which is the UI of my application.

Is this an issue? How can I solve this?
