### ISSUE TITLE
Add resource.requests and resource.limits

### ISSUE THREAD

**Issue by AljoschaP** [minio/charts#67]
Hello everybody,

is there any reason why cpu/memory requests and limits can't be set ?

```
resources:
  requests:
    memory: 512Mi
    cpu: 0.25
  limits:
    memory: 512Mi
    cpu: 0.25

```
Thank you :-)
