### ISSUE TITLE
FR => minio-ha-make-bucket-job fails (on purpose?)

### ISSUE THREAD

**Issue by aeimer** [minio/charts#72]
I updated from version `8.0.3` to version `8.0.5` and also added a:

```yaml
buckets:
  - name: loki
  - name: ruler
```

Which fails with a

![grafik](https://user-images.githubusercontent.com/25035182/100371477-1a0f1600-3008-11eb-9a6d-bee0fe4b5b28.png)

I would like to have some defaults set or have the bash script handle that better.

It would be great to either provide only a list of strings (as names) or provide objects in the array but with some good defaults in the helm or script.
So I'd like to be able to insert:

```yaml
buckets:
- bucket 1
- bucket 2

# OR

buckets:
- name: bucket 0
- name: bucket 1
  purge: true
- name: bucket 2
  policy: public
- name: bucket 3
  policy: none
  purge: true
```
