### ISSUE TITLE
simple distributed setup example

### ISSUE THREAD

**Issue by patvdleer** [minio/charts#73]
Forgive my noobishness, Im new to Minio, when setting up a simple setup in KinD Im unable to get it up and running

```sh
helm repo add minio https://helm.min.io/
helm install --set mode=distributed my-release minio/minio
```
results in:

```
ERROR Invalid command line arguments: path '/export' can not be served by different port on same address
      > Please provide correct combination of local/remote paths
      HINT:
        For more information, please refer to https://docs.min.io/docs/minio-erasure-code-quickstart-guide
```

Im trying to run this on a KinD setup:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # disableDefaultCNI: True
  # serviceSubnet: "172.30.0.0/16"
  # podSubnet: "10.254.0.0/16"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
  - role: worker
```
