### ISSUE TITLE
Additional buckets are not created

### ISSUE THREAD

**Issue by omerfsen** [minio/charts#77]
When we deploy the helm chart

```yaml
  install: true
  defaultBucket:
    enabled: true
    name: {{artifact_name}}
  persistence:
    size: {{artifact_size}}
    accessMode: ReadWriteMany
    storageClass: "nfs"
  tls:
    enabled: true
    certSecret: {{ingress_secret}}
    publicCrt: tls.crt
    privateKey: tls.key
  nodeSelector:
    beta.kubernetes.io/os: "linux"
    agentpool: service
  # Default is 4Gi
  resources:
    requests:
      memory: 2Gi
  accessKey: "{{rtifact_accesskey}}"
  secretKey: "{{artifact_secretkey}}"
  # Additional Buckets
  buckets:
    - name: plx-storage
      policy: none
      purge: false
    - name: tmp-bucket
      policy: none
      purge: false
      ## set versioning for bucket true|false
      # versioning: false

````

Additional buckets are not created (above examples plx-storage and tmp-bucket) but  defaultBucket is created

**Comment by omerfsen** [comment]
I used latest 8.0.5 version  (And 8.0.0) of chart.

**Comment by omerfsen** [comment]
I also commented out defaultBucket and added buckets name to buckets list  and only first bucket is created (**test** bucket  in following case)

```yaml


  #defaultBucket:
  #  enabled: true
  #  name: test
  buckets:
    - name: test
      policy: none
      purge: false
    - name: plx-storage
      policy: none
      purge: false
    - name: tmp-bucket
      policy: none
      purge: false
      ## set versioning for bucket true|false
      # versioning: false
```
