### ISSUE TITLE
readiness missing

### ISSUE THREAD

**Issue by kfirfer** [minio/charts#84]
Hello

in the chart release 8+ I could see that readiness is missing

In my opinion it is necessery when working with distributed mode and kubernetes services + ingresses

when a node is ungracefully down, the traffic from outside are miss behaves

What do you think ?

**Comment by harshavardhana** [comment]
It's on purpose readiness is actually not worth use you may use liveness.

MinIO implements necessary semantics to reroute your request if system is not ready.

**Comment by kfirfer** [comment]
> MinIO implements necessary semantics to reroute your request if system is not ready.

Unfortunately it is not whats happening
Tested with chart version 8.0.8

**Comment by kfirfer** [comment]
When the minio web server itself is not ready yet to accept  traffic, the kubernetes service hits and return error

**Comment by harshavardhana** [comment]
> When the MinIO web server itself is not ready yet to accept traffic(+reroute), the kubernetes service try to hit and return error

Of course it won't if the service is not ready there is no point even having readiness. Readiness doesn't do anything other than interfere with our startup sequence. 

It is never useful.

**Comment by kfirfer** [comment]
It is not entirely correct,
You need readiness to check with a healthcheck script if MinIO webserver is up/down
In order to avoid hits a down webserver

**Comment by kfirfer** [comment]
Kubernetes readiness does not meant to interfere, it is meant to solve this type of problems

**Comment by kfirfer** [comment]
Example cluster setup, traffic flow from the client to the MinIO data file itself:

GET /data (browser) ->
 Linux machine NIC ->
 MetalLB (Load balancer) ->
 NginX controller Ingress (Proxy & Loadbalancer) ->
 K8S service(endpoint) (Proxy & Loadbalancer) ->
 MinIO webserver ->
 MinIO data files

For maximum high availability, need to have load balance any step above with readiness mechanism each one to the next

**Comment by kfirfer** [comment]
> you may use liveness

Its not good advice to have liveness on stateful applications, it can lead to Split brain scenarios / data corruption

**Comment by harshavardhana** [comment]
> Its not good advice to have liveness on stateful applications, it can lead to Split brain scenarios / data corruption

Not really @kfirfer MinIO handles split brain situations - none of these features in k8s make sense for us. So you can turn all of them off and you will be fine.

**Comment by kfirfer** [comment]
I wish I could say the same, but no matter what I do, Im keep getting miss behaves situations , I traced the logs and nothing helped me out... I could give you control on my Kubernetes cluster and you would see it if you want to

Meanwhile, I have a custom chart that I written , I want to use the mainstream Chart, but at this moment I cant...

**Comment by kfirfer** [comment]
I tried at this very moment tests about how MinIO handles ungracefully shutdown of one nodes

Having 3 kubernetes nodes, setup with chart 8.0.8 and this is the overiden values:



```
accessKey: XXXXXXX
secretKey: XXXXXXX

mode: distributed

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "0"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/limit-connections: "1000"
    nginx.ingress.kubernetes.io/limit-rps: "1000"
    nginx.ingress.kubernetes.io/limit-rate: "1000"
    nginx.ingress.kubernetes.io/enable-opentracing: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: saffer";
      proxy_hide_header "content-security-policy";
      proxy_hide_header "x-powered-by";
      more_set_headers "X-Xss-Protection: 1; mode=block";
  hosts:
    - minio-test.tatzan.com
  tls:
    - hosts:
        - "*.tatzan.com"

drivesPerNode: 2
replicas: 3

persistence:
  size: 10Gi

defaultBucket:
  enabled: true
  name: kfir

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 2Gi
    cpu: 4000m

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - minio
        topologyKey: "kubernetes.io/hostname"

tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
```

And the MinIO browser shows this 1/3 of the times : 

![Selection_005](https://user-images.githubusercontent.com/7741545/101996034-988dd800-3cd7-11eb-9f95-0ccd91ee7093.jpg)

Tooks around 2-4 minutes to come back normally
