### ISSUE TITLE
Permissions issue deploying MinIO on Kubernetes

### ISSUE THREAD

**Issue by IrvingMg** [minio/charts#96]
Hello everyone,

I'm having an issue deploying the MinIO chart on Kubernetes. I'm trying to deploy MinIO on distributed mode using Persistent Volumes with hostPath.

In order to make the deployment, first I created the `Persistent Volumes`using `hostPath` to the `/tmp` directory. Below is the yaml file:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /tmp/minio/data01
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /tmp/minio/data02
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-3
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /tmp/minio/data03
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-4
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /tmp/minio/data04
  persistentVolumeReclaimPolicy: Recycle

```

then, I'm creating the `Persistent Volume Claims` using the following file:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: export-minio-3
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

```

and finally, I deployed the chart providing a [values.yaml](https://github.com/minio/charts/blob/master/minio/values.yaml) file with `mountPath: "/data"`. However, the deployment of the pods fails with this error:

```none
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Run the following command to add write permissions: `sudo chown -R <your-username> /data && sudo chmod u+rxw /data`
```

What might it be the cause of this isse?

**Comment by ArtemAlagizov** [comment]
it seems to be an issue with permissions (for **/export** folder inside the minio container).

there is a pull request that aims at fixing it => https://github.com/minio/charts/pull/70

meanwhile, you can disable securityContext (not recommended for production, of course)
  ```
  helm install minio-storage minio/minio --set securityContext.enabled=false
  ```

maybe, somebody here can recommend a better approach, let's see

**Comment by IrvingMg** [comment]
Hi @ArtemAlagizov thank you for replying! I updated my PVs to use local provisioner and that error has gone but now I have new one. Here is the new error: 
```
Disk `/data` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Waiting for a minimum of 2 disks to come online (elapsed 9s)
```

My PVs are like this:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-0
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /tmp/minio/data00
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-8-109
```
I found a similar issue [10519](https://github.com/minio/minio/issues/10519#issue-704820288) and as I understand, I need to mount a second volume on one of the nodes to avoid using the root disk, right?. So I did that, I mounted the volume `nvme1n1 ` on one worker node. The output of `lsblk` is: 

```
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0         7:0    0 97.9M  1 loop /snap/core/10577
loop1         7:1    0 32.3M  1 loop /snap/amazon-ssm-agent/2996
loop2         7:2    0 28.1M  1 loop /snap/amazon-ssm-agent/2012
loop3         7:3    0 97.9M  1 loop /snap/core/10583
loop4         7:4    0 55.4M  1 loop /snap/core18/1944
loop5         7:5    0 70.6M  1 loop /snap/lxd/16922
loop6         7:6    0 67.8M  1 loop /snap/lxd/18150
loop7         7:7    0 55.3M  1 loop /snap/core18/1885
nvme0n1     259:0    0    8G  0 disk 
└─nvme0n1p1 259:1    0    8G  0 part /
nvme1n1     259:2    0    4G  0 disk /data
```
However, I'm still getting the error message of refusing to use root disk. So I'm a little lost on how should the configuration for distributed mode be. Any guidance to deploy Minio in distributed mode without a provisioner storage would be appreciated
